# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G -Djava.io.tmpdir=C:/Users/mixpl/AppData/Local/Temp
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.19.5
# Mod Properties
mod_version=1.0.1-SNAPSHOT
maven_group=com.mixplus.mods
archives_base_name=uuidcommand
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.136.1+1.21.8

org.gradle.java.home=C:/java/java21
